feat: added first workflow file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,16 +1,20 @@
 name: 01 - Building Blocks
-  on: [push, workflow_dispatch]
+
+on: [push, workflow_dispatch]
 
 jobs:
-  name: echo-hello
+  echo-hello:
     runs-on: ubuntu-latest
     steps:
-      - name: Echo Hello
+      - name: Say Hello
         run: echo "Hello"
-  name: echo-goodbye
+  
+  echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-      name: Failed step
-        run: echo "I will fail?" && exit 1
-      name: Say Goodbye
+      - name: Failed step
+        run: |
+          echo "I will fail?"
+          exit 1
+      - name: Say Goodbye
         run: echo "Goodbye!"
